import os
import uuid
from datetime import datetime

import boto3
from botocore.exceptions import ClientError
from flask import Flask, request, jsonify
from dotenv import load_dotenv

#  Load environment variables from .env file
load_dotenv()

#  Initialize Flask app
app = Flask(__name__)

#  Load configuration from environment variables
AWS_REGION = os.getenv("AWS_REGION", "eu-west-1")
S3_BUCKET = os.getenv("S3_BUCKET", "facesof-people")
COLLECTION_ID = os.getenv("COLLECTION_ID", "facerekogn")
DYNAMODB_TABLE = os.getenv("DYNAMODB_TABLE", "face_recognition")

#  Initialize AWS clients
s3 = boto3.client("s3", region_name=AWS_REGION)
rekognition = boto3.client("rekognition", region_name=AWS_REGION)
dynamodb = boto3.resource("dynamodb", region_name=AWS_REGION)

#  Reference DynamoDB table
table = dynamodb.Table(DYNAMODB_TABLE)



#  Helper Function: Upload file to S3
def upload_file_to_s3(file_obj, filename, metadata=None, folder="uploads"):
    """
    Uploads a file to S3 with optional metadata.

    Args:
        file_obj: File object from request
        filename: Original file name
        metadata: Dictionary of metadata (e.g., fullname)
        folder: S3 folder (e.g., registered, search)

    Returns:
        s3_key: Path of uploaded file in S3
    """

    #  Generate a unique filename to avoid overwriting
    s3_key = f"{folder}/{uuid.uuid4()}_{filename}"

    #  Define extra upload parameters
    extra_args = {
        "ContentType": file_obj.content_type or "image/jpeg"
    }

    #  Attach metadata if provided (must be lowercase keys)
    if metadata:
        extra_args["Metadata"] = metadata

    #  Upload file to S3
    s3.upload_fileobj(file_obj, S3_BUCKET, s3_key, ExtraArgs=extra_args)

    return s3_key



#  Route: Home
@app.route("/", methods=["GET"])
def home():
    """Basic route to check if API is running"""
    return jsonify({
        "message": "Face Recognition API is running"
    })



# Route: Register Face
@app.route("/register", methods=["POST"])
def register_face():
    """
    Registers a new face:
    1. Upload image to S3
    2. Index face into Rekognition collection
    3. Store face details in DynamoDB
    """

    try:
        #  Check if image is provided
        if "image" not in request.files:
            return jsonify({"error": "Image file is required"}), 400

        #  Get full name from request
        full_name = request.form.get("full_name")
        if not full_name:
            return jsonify({"error": "full_name is required"}), 400

        image = request.files["image"]

        #  Add metadata (important for later use)
        metadata = {"fullname": full_name}

        #  Upload image to S3 under "registered" folder
        s3_key = upload_file_to_s3(
            image,
            image.filename,
            metadata=metadata,
            folder="registered"
        )

        #  Send image to Rekognition for face indexing
        response = rekognition.index_faces(
            CollectionId=COLLECTION_ID,
            Image={
                "S3Object": {
                    "Bucket": S3_BUCKET,
                    "Name": s3_key
                }
            },
            DetectionAttributes=[]
        )

        #  Extract detected face records
        face_records = response.get("FaceRecords", [])

        #  If no face found, return error
        if not face_records:
            return jsonify({
                "error": "No face detected in the uploaded image"
            }), 400

        #  Get FaceId generated by Rekognition
        face_id = face_records[0]["Face"]["FaceId"]

        #  Store face details in DynamoDB
        table.put_item(
            Item={
                "RekognitionId": face_id,
                "FullName": full_name,
                "Bucket": S3_BUCKET,
                "ImageKey": s3_key,
                "CreatedAt": datetime.utcnow().isoformat()
            }
        )

        #  Return success response
        return jsonify({
            "message": "Face registered successfully",
            "FaceId": face_id,
            "FullName": full_name,
            "ImageKey": s3_key
        }), 201

    except ClientError as e:
        return jsonify({"error": str(e)}), 500
    except Exception as e:
        return jsonify({"error": str(e)}), 500



# Route: Recognize Face

@app.route("/recognize", methods=["POST"])
def recognize_face():
    """
    Recognizes a face:
    1. Upload image to S3
    2. Search face in Rekognition collection
    3. Fetch matching person from DynamoDB
    """

    try:
        # Check if image is provided
        if "image" not in request.files:
            return jsonify({"error": "Image file is required"}), 400

        image = request.files["image"]

        # Upload image to S3 under "search" folder
        s3_key = upload_file_to_s3(
            image,
            image.filename,
            folder="search"
        )

        #  Search face in Rekognition collection
        response = rekognition.search_faces_by_image(
            CollectionId=COLLECTION_ID,
            Image={
                "S3Object": {
                    "Bucket": S3_BUCKET,
                    "Name": s3_key
                }
            },
            MaxFaces=1,
            FaceMatchThreshold=80
        )

        # Extract matches
        matches = response.get("FaceMatches", [])

        # No match found
        if not matches:
            return jsonify({
                "message": "No match found",
                "ImageKey": s3_key
            }), 404

        # Get best match
        best_match = matches[0]
        face_id = best_match["Face"]["FaceId"]
        similarity = best_match["Similarity"]

        #  Fetch person details from DynamoDB
        result = table.get_item(Key={"RekognitionId": face_id})
        item = result.get("Item")

        # If not found in DB
        if not item:
            return jsonify({
                "message": "Face matched but not found in database",
                "FaceId": face_id,
                "Similarity": similarity
            }), 404

        #  Return match result
        return jsonify({
            "message": "Match found",
            "FaceId": face_id,
            "Similarity": similarity,
            "FullName": item.get("FullName"),
            "Bucket": item.get("Bucket"),
            "ImageKey": item.get("ImageKey"),
            "SearchImageKey": s3_key
        }), 200

    except ClientError as e:
        return jsonify({"error": str(e)}), 500
    except Exception as e:
        return jsonify({"error": str(e)}), 500



# Run Flask App
if __name__ == "__main__":
    app.run(debug=True)